2018-02-23 23:08:54,756 - ReadLogDoKafka - DEBUG - {'test1': <weakref at 0000000006495408; to 'Topic' at 00000000064A3780>, 'aa': None, 'list1': None}
2018-02-23 23:08:54,759 - FileFlow - DEBUG - **************************************start read at offset 6676******************************
2018-02-23 23:29:58,871 - ReadLogDoKafka - DEBUG - {'test1': <weakref at 000000000577F5E8; to 'Topic' at 000000000578A940>, 'aa': None, 'list1': None}
2018-02-23 23:29:58,872 - LogReader - ERROR - init file_flow Exception catched:('File {} not found', 'test_long.log')
2018-02-23 23:29:58,872 - LogReader - ERROR - file_flow.read_file NameError catched:name 'file_flow' is not defined
2018-02-23 23:30:26,473 - ReadLogDoKafka - DEBUG - {'test1': <weakref at 0000000005EB8598; to 'Topic' at 0000000005EC2978>, 'aa': None, 'list1': None}
2018-02-23 23:30:26,474 - LogReader - ERROR - init file_flow Exception catched:('File {} not found', 'test_long.log')
2018-02-23 23:30:26,474 - LogReader - ERROR - file_flow.read_file NameError catched:name 'file_flow' is not defined
2018-02-23 23:35:40,792 - LogReader - ERROR - create reader NoOptionError catched:No option 'topic' in section: 'KAFKA'
2018-02-23 23:35:40,793 - LogReader - ERROR - init file_flow NameError catched:name 'reader' is not defined
2018-02-23 23:35:40,793 - LogReader - ERROR - file_flow.read_file NameError catched:name 'file_flow' is not defined
2018-02-23 23:36:12,417 - ReadLogDoKafka - DEBUG - {'test1': <weakref at 0000000005767598; to 'Topic' at 000000000576BB70>, 'aa': None, 'list1': None}
2018-02-23 23:36:12,418 - LogReader - ERROR - init file_flow ValueError catched:invalid literal for int() with base 10: "'4096'"
2018-02-23 23:36:12,418 - LogReader - ERROR - file_flow.read_file NameError catched:name 'file_flow' is not defined
2018-02-23 23:36:44,223 - ReadLogDoKafka - DEBUG - {'test1': <weakref at 0000000005B97598; to 'Topic' at 0000000005B9BB70>, 'aa': None, 'list1': None}
2018-02-23 23:36:44,223 - LogReader - ERROR - init file_flow Exception catched:('File {} not found', "'test.log'")
2018-02-23 23:36:44,223 - LogReader - ERROR - file_flow.read_file NameError catched:name 'file_flow' is not defined
2018-02-23 23:37:19,706 - ReadLogDoKafka - DEBUG - {'test1': <weakref at 0000000005F37598; to 'Topic' at 0000000005F3BB70>, 'aa': None, 'list1': None}
2018-02-23 23:37:19,707 - FileFlow - DEBUG - **************************************start read at offset 6676******************************
